import { chromium, devices } from 'playwright';
const b = await chromium.launch({ headless: true });
const p = await (await b.newContext({ ...devices['iPhone 13'] })).newPage();
const bad = [];
p.on('response', r => { if (r.status() >= 400) bad.push(`${r.status()} ${r.url().replace('https://pp771007.github.io/idle-lineage-class/','')}`); });
await p.goto('https://pp771007.github.io/idle-lineage-class/?cb=' + Date.now(), { waitUntil: 'domcontentloaded', timeout: 90000 });
await p.waitForTimeout(4000);
await p.evaluate(() => { openSlotSelect('new'); chooseSlot(1); selectClass('m_knight'); startGame(); });
await p.waitForTimeout(6000);
console.log('=== 4xx/5xx ===');
console.log(bad.length ? [...new Set(bad)].join('\n') : 'none');
await b.close();
